"""Estados e transicoes permitidas. Dois niveis: job e corte."""
from __future__ import annotations

# --- job (um episodio)
NOVO = "NOVO"
SEM_LEGENDA = "SEM_LEGENDA"
LEGENDA_OBTIDA = "LEGENDA_OBTIDA"
SEGMENTADO = "SEGMENTADO"
SEM_CORTES = "SEM_CORTES"
RENDERIZADO = "RENDERIZADO"
CONCLUIDO = "CONCLUIDO"
ERRO = "ERRO"

# --- corte (um trecho; N por job)
AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO"
APROVADO = "APROVADO"
PUBLICADO = "PUBLICADO"
ERRO_UPLOAD = "ERRO_UPLOAD"
REJEITADO = "REJEITADO"
REFAZER = "REFAZER"
ERRO_RENDER = "ERRO_RENDER"

TRANSICOES_JOB: dict[str, set[str]] = {
    NOVO: {LEGENDA_OBTIDA, SEM_LEGENDA, ERRO},
    LEGENDA_OBTIDA: {SEGMENTADO, SEM_CORTES, ERRO},
    SEGMENTADO: {RENDERIZADO, ERRO},
    RENDERIZADO: {CONCLUIDO, SEGMENTADO, ERRO},
    ERRO: {NOVO},
    SEM_LEGENDA: set(),
    SEM_CORTES: set(),
    CONCLUIDO: set(),
}

TRANSICOES_CORTE: dict[str, set[str]] = {
    AGUARDANDO_APROVACAO: {APROVADO, REJEITADO, REFAZER},
    APROVADO: {PUBLICADO, ERRO_UPLOAD},
    ERRO_UPLOAD: {APROVADO, REJEITADO},
    REFAZER: {AGUARDANDO_APROVACAO, ERRO_RENDER},
    ERRO_RENDER: {REFAZER, REJEITADO},
    PUBLICADO: set(),
    REJEITADO: set(),
}

JOB_FINAIS = {SEM_LEGENDA, SEM_CORTES, CONCLUIDO}
CORTE_PENDENTES = {AGUARDANDO_APROVACAO, APROVADO, ERRO_UPLOAD, REFAZER}


def pode(mapa: dict[str, set[str]], de: str, para: str) -> bool:
    return para in mapa.get(de, set())
